# Generated by Django 4.2.4 on 2023-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
